apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  parentRefs:
    - name: gateway
      sectionName: http
      namespace: gateway
  hostnames:
    - "argocd.local"
  rules:
    - matches:
      - path:
          type: PathPrefix # Matches any path starting with /coffee
          value: "/"
      backendRefs:
        - name: argocd-server
          port: 443